/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.imepac.administrativo.telas.Perfil;

/**
 *
 * @author User
 */
public class EditarPerfil extends javax.swing.JFrame {

    /**
     * Creates new form EditarPerfil
     */
    public EditarPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ListarFuncionario = new javax.swing.JComboBox<>();
        ListarProntuario = new javax.swing.JComboBox<>();
        EditarFuncionario = new javax.swing.JComboBox<>();
        CriarFuncionario = new javax.swing.JComboBox<>();
        CriarPaciente = new javax.swing.JComboBox<>();
        EditarPaciente = new javax.swing.JComboBox<>();
        ListarPaciente = new javax.swing.JComboBox<>();
        ListarConsulta = new javax.swing.JComboBox<>();
        EditarConsulta = new javax.swing.JComboBox<>();
        CriarConsulta = new javax.swing.JComboBox<>();
        CriarEspecialidade = new javax.swing.JComboBox<>();
        ListarConvenio = new javax.swing.JComboBox<>();
        CriarProntuario = new javax.swing.JComboBox<>();
        EditarProntuario = new javax.swing.JComboBox<>();
        EditarEspecialidade = new javax.swing.JComboBox<>();
        ListarEspecialidade = new javax.swing.JComboBox<>();
        CriarConvenio = new javax.swing.JComboBox<>();
        EditarConvenio = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Edição Perfil");

        jPanel2.setLayout(null);

        jLabel4.setText("Funcionario");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 90, 80, 16);

        jLabel5.setText("Paciente");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(170, 90, 70, 16);

        jLabel6.setText("Consulta");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(270, 90, 70, 16);

        jLabel9.setText("Prontuário");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(370, 90, 70, 16);

        jLabel3.setText("Especialidade");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(470, 90, 90, 16);

        jLabel7.setText("Convênio");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(570, 90, 80, 16);

        jButton2.setText("Salvar ");
        jPanel2.add(jButton2);
        jButton2.setBounds(430, 240, 72, 23);

        jButton1.setText("Cancelar");
        jPanel2.add(jButton1);
        jButton1.setBounds(610, 240, 76, 23);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(92, 15, 231, 22);

        jLabel2.setText("Nome do Perfil");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(6, 18, 80, 16);

        jLabel8.setText("Listar");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 180, 41, 16);

        jButton3.setText("Apagar");
        jPanel2.add(jButton3);
        jButton3.setBounds(520, 240, 72, 23);

        jPanel2.add(jComboBox7);
        jComboBox7.setBounds(92, 49, 231, 22);

        jLabel10.setText("ID Perfil");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(6, 52, 41, 16);

        jLabel11.setText("Criar");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 120, 25, 16);

        jLabel12.setText("Editar");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 150, 41, 16);

        ListarFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(ListarFuncionario);
        ListarFuncionario.setBounds(70, 180, 70, 22);

        ListarProntuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(ListarProntuario);
        ListarProntuario.setBounds(370, 180, 70, 22);

        EditarFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(EditarFuncionario);
        EditarFuncionario.setBounds(70, 150, 70, 22);

        CriarFuncionario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        CriarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarFuncionarioActionPerformed(evt);
            }
        });
        jPanel2.add(CriarFuncionario);
        CriarFuncionario.setBounds(70, 120, 70, 22);

        CriarPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        CriarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarPacienteActionPerformed(evt);
            }
        });
        jPanel2.add(CriarPaciente);
        CriarPaciente.setBounds(170, 120, 70, 22);

        EditarPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(EditarPaciente);
        EditarPaciente.setBounds(170, 150, 70, 22);

        ListarPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(ListarPaciente);
        ListarPaciente.setBounds(170, 180, 70, 22);

        ListarConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(ListarConsulta);
        ListarConsulta.setBounds(270, 180, 70, 22);

        EditarConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(EditarConsulta);
        EditarConsulta.setBounds(270, 150, 70, 22);

        CriarConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(CriarConsulta);
        CriarConsulta.setBounds(270, 120, 70, 22);

        CriarEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(CriarEspecialidade);
        CriarEspecialidade.setBounds(470, 120, 70, 22);

        ListarConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(ListarConvenio);
        ListarConvenio.setBounds(570, 180, 70, 22);

        CriarProntuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        CriarProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CriarProntuarioActionPerformed(evt);
            }
        });
        jPanel2.add(CriarProntuario);
        CriarProntuario.setBounds(370, 120, 70, 22);

        EditarProntuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(EditarProntuario);
        EditarProntuario.setBounds(370, 150, 70, 22);

        EditarEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(EditarEspecialidade);
        EditarEspecialidade.setBounds(470, 150, 70, 22);

        ListarEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(ListarEspecialidade);
        ListarEspecialidade.setBounds(470, 180, 70, 22);

        CriarConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(CriarConvenio);
        CriarConvenio.setBounds(570, 120, 70, 22);

        EditarConvenio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sim", "Não" }));
        jPanel2.add(EditarConvenio);
        EditarConvenio.setBounds(570, 150, 70, 22);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 598, Short.MAX_VALUE))
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void CriarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CriarPacienteActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void CriarProntuarioActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> CriarConsulta;
    private javax.swing.JComboBox<String> CriarConvenio;
    private javax.swing.JComboBox<String> CriarEspecialidade;
    private javax.swing.JComboBox<String> CriarFuncionario;
    private javax.swing.JComboBox<String> CriarPaciente;
    private javax.swing.JComboBox<String> CriarProntuario;
    private javax.swing.JComboBox<String> EditarConsulta;
    private javax.swing.JComboBox<String> EditarConvenio;
    private javax.swing.JComboBox<String> EditarEspecialidade;
    private javax.swing.JComboBox<String> EditarFuncionario;
    private javax.swing.JComboBox<String> EditarPaciente;
    private javax.swing.JComboBox<String> EditarProntuario;
    private javax.swing.JComboBox<String> ListarConsulta;
    private javax.swing.JComboBox<String> ListarConvenio;
    private javax.swing.JComboBox<String> ListarEspecialidade;
    private javax.swing.JComboBox<String> ListarFuncionario;
    private javax.swing.JComboBox<String> ListarPaciente;
    private javax.swing.JComboBox<String> ListarProntuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
}
